### ISSUE TITLE
CI isn't running for this repo

### ISSUE THREAD

**Issue by dalemyers** [microsoft/dotstrings#3]
It should be running this pipeline: https://outlookmobile.visualstudio.com/Github/_build?definitionId=84 

@levinli303 can you take a quick look at this? It would have caught a bunch of stuff in your PR.

**Comment by levinli303** [comment]
hmm, is that we need to add trigger in .yml?

**Comment by dalemyers** [comment]
Probably :)

**Comment by dalemyers** [comment]
Perhaps not: https://github.com/microsoft/dotstrings/commit/42993b5b58088160b27555400e92dfd75a851519

**Comment by levinli303** [comment]
could be something in GitHub settings of this repo or on ADO? I don't have permission in either place

**Comment by dalemyers** [comment]
Me neither. Mine were all removed when I left. Corbin and Lance are admins in here I think. And John Lotito is definitely an admin on the outlookmobile ADO instance. There could be others.

**Comment by MikeChongCan** [comment]
@levinli303 I will be pinging you about the details.

**Comment by levinli303** [comment]
I re-added the pipeline and it seems to be working now
